server:
  port: 8080

spring:
  application:
    name: exchange-crypto

  datasource:
    url: ${DBMS_CONNECTION}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
    driver-class-name: "com.mysql.cj.jdbc.Driver"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
#      password: ${REDIS_PASSWORD}
      database: 0
      timeout: 1000 # in milliseconds

auth:
  signer-key: ${SIGNER_KEY}
  valid-duration: 86400 # in second : 1 day
  refreshable-duration: 259200 # in second

app:
  binance:
    websocket-url: wss://stream.binance.com:9443/ws
    ticker-symbols: btcusdt, ethusdt, adausdt, dotusdt, bnbusdt, solusdt

  websocket:
    thread-pool:
      core-size: 5
      max-size: 20
      queue-capacity: 500