server:
  port: 8080

spring:
  application:
    name: exchange-crypto

  datasource:
    #    url: ${DBMS_URL:jdbc:mysql://localhost:3306/socialnetworkdb}
    #    username: ${DBMS_USERNAME:root}
    #    password: ${DBMS_PASSWORD:tiendatmySQL964@}

    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/exchangecrypto}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:tiendatmySQL964@}
    driver-class-name: "com.mysql.cj.jdbc.Driver"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#auth:
#  signer-key: "9IkbhtRXgJZF9CA3SerRWlpiytQBLJFXpCRx58oFZu2zOvGtoJAC4b257tfa8rmd"
#  valid-duration: 36000 # in second
#  refreshable-duration: 360000 # in second
